sudo: required
language: generic

# see https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx

install:
  - if [ "$TRAVIS_OS_NAME" == "osx"   ] ; then   ci/install-osx.sh ; fi

script:
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - python src/tests/runtests.py
