version: '{branch}-{build}'
build: off

platform:
  - x86
  - x64

environment:
  global:
    PYTHONUNBUFFERED: True
    PYTHONWARNINGS: 'ignore:::wheel.pep425tags:'
    PYTHONPATH: C:\testdir
    NUNIT: nunit3-console
    CONDA_BLD: C:\miniconda35

  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.3
    - PYTHON_VERSION: 3.4
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6

init:
  # Prepare environment
  - mkdir C:\testdir

  # Set environment variables depending based on build cfg
  - set CONDA_PY=%PYTHON_VERSION:.=%
  - set CONDA_BLD_ARCH=%PLATFORM:x=%
  - set PYTHON=C:\PYTHON%PYTHON_VERSION:.=%
  - if %PLATFORM%==x86 (set CONDA_BLD_ARCH=32)
  # - if %PLATFORM%==x86 (set NUNIT=%NUNIT%-x86)
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)
  - if %PLATFORM%==x64 (set CONDA_BLD=%CONDA_BLD%-x64)

  # Prepend newly installed Python to the PATH of this build
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version, architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -c "import ctypes; print(ctypes.sizeof(ctypes.c_wchar))"

install:
  # install for wheels & coverage
  - pip install --upgrade pip wheel coverage codecov pytest

  # Install OpenCover. Can't put on packages.config; not Linux/Mono compatible
  - .\tools\nuget\nuget.exe install OpenCover -OutputDirectory packages

build_script:
  # build clean sdist & wheel with coverage of setup.py, install local wheel
  - coverage run setup.py sdist bdist_wheel

test_script:
  - pip install --no-index --find-links=.\dist\ pythonnet
  - ps: Copy-Item (Resolve-Path .\build\*\Python.Test.dll) C:\testdir

  # Test runner
  - ps: .\ci\appveyor_run_tests.ps1

  # Build conda-recipe on Pull Requests
  - ps: .\ci\appveyor_build_recipe.ps1

on_finish:
  # Upload coverage
  - dir

artifacts:
  - path: dist\*

cache:
  # preserve `packages` directory; will reset if `packages.config` is modified
  - packages -> **\packages.config
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'
